// ============================================
// KHARA 케이하라 - Product Data
// ============================================

const PRODUCTS = [
  // === K-FOOD ===
  {
    id: 'kf-001',
    name: 'Buldak Hot Chicken Ramen (5-Pack)',
    nameKr: '불닭볶음면 5개입',
    category: 'k-food',
    subcategory: 'ramen',
    price: 8.99,
    originalPrice: 11.99,
    discount: 25,
    rating: 4.8,
    reviews: 2341,
    badges: ['hot'],
    emoji: '🍜',
    bgColor: '#fff3e0',
    description: 'The viral sensation! Super spicy stir-fried chicken flavor ramen from Samyang.',
    inStock: true
  },
  {
    id: 'kf-002',
    name: 'Honey Butter Chips',
    nameKr: '허니버터칩',
    category: 'k-food',
    subcategory: 'snacks',
    price: 4.99,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviews: 1876,
    badges: [],
    emoji: '🍯',
    bgColor: '#fff8e1',
    description: 'Korea\'s most famous chip! Sweet honey and savory butter flavor.',
    inStock: true
  },
  {
    id: 'kf-003',
    name: 'Gochujang Red Pepper Paste 500g',
    nameKr: '고추장 500g',
    category: 'k-food',
    subcategory: 'sauce',
    price: 7.49,
    originalPrice: null,
    discount: 0,
    rating: 4.9,
    reviews: 3102,
    badges: [],
    emoji: '🌶️',
    bgColor: '#fce4ec',
    description: 'Essential Korean fermented chili paste for authentic cooking.',
    inStock: true
  },
  {
    id: 'kf-004',
    name: 'Banana Milk 6-Pack',
    nameKr: '바나나맛 우유 6개입',
    category: 'k-food',
    subcategory: 'drinks',
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    rating: 4.7,
    reviews: 1543,
    badges: ['sale'],
    emoji: '🍌',
    bgColor: '#fffde7',
    description: 'Iconic Korean banana flavored milk in the classic jar shape.',
    inStock: true
  },
  {
    id: 'kf-005',
    name: 'Tteokbokki Rice Cake Kit',
    nameKr: '떡볶이 밀키트',
    category: 'k-food',
    subcategory: 'traditional',
    price: 9.99,
    originalPrice: null,
    discount: 0,
    rating: 4.5,
    reviews: 892,
    badges: ['new'],
    emoji: '🍡',
    bgColor: '#fce4ec',
    description: 'Make authentic spicy rice cakes at home with this complete kit.',
    inStock: true
  },
  {
    id: 'kf-006',
    name: 'Korean BBQ Sauce Set',
    nameKr: '한국식 바베큐 소스 세트',
    category: 'k-food',
    subcategory: 'sauce',
    price: 18.99,
    originalPrice: 24.99,
    discount: 24,
    rating: 4.8,
    reviews: 654,
    badges: ['sale'],
    emoji: '🥩',
    bgColor: '#efebe9',
    description: 'Premium galbi and bulgogi marinade sauce set for the perfect Korean BBQ.',
    inStock: true
  },

  // === K-BEAUTY ===
  {
    id: 'kb-001',
    name: 'COSRX Snail Mucin Essence 96%',
    nameKr: '코스알엑스 달팽이 무친 에센스',
    category: 'k-beauty',
    subcategory: 'skincare',
    price: 21.99,
    originalPrice: 25.00,
    discount: 12,
    rating: 4.9,
    reviews: 8923,
    badges: ['hot'],
    emoji: '✨',
    bgColor: '#f3e5f5',
    description: 'TikTok-famous hydrating essence with 96% snail secretion filtrate.',
    inStock: true
  },
  {
    id: 'kb-002',
    name: 'Innisfree Green Tea Seed Serum',
    nameKr: '이니스프리 그린티 씨드 세럼',
    category: 'k-beauty',
    subcategory: 'skincare',
    price: 27.00,
    originalPrice: null,
    discount: 0,
    rating: 4.7,
    reviews: 4521,
    badges: [],
    emoji: '🍵',
    bgColor: '#e8f5e9',
    description: 'Deeply hydrating serum with Jeju green tea for moisture-rich skin.',
    inStock: true
  },
  {
    id: 'kb-003',
    name: 'TONYMOLY Sheet Mask Variety (10pcs)',
    nameKr: '토니모리 시트마스크 10매',
    category: 'k-beauty',
    subcategory: 'masks',
    price: 14.99,
    originalPrice: 19.99,
    discount: 25,
    rating: 4.6,
    reviews: 3211,
    badges: ['sale'],
    emoji: '🧖',
    bgColor: '#e0f7fa',
    description: 'Assorted sheet masks including snail, rice, green tea, and more.',
    inStock: true
  },
  {
    id: 'kb-004',
    name: 'BEAUTY OF JOSEON Sunscreen SPF50+',
    nameKr: '조선미녀 선크림 SPF50+',
    category: 'k-beauty',
    subcategory: 'suncare',
    price: 16.99,
    originalPrice: null,
    discount: 0,
    rating: 4.9,
    reviews: 6543,
    badges: ['hot'],
    emoji: '☀️',
    bgColor: '#fff8e1',
    description: 'Lightweight, no white cast sunscreen loved by skincare enthusiasts worldwide.',
    inStock: true
  },
  {
    id: 'kb-005',
    name: 'LANEIGE Lip Sleeping Mask',
    nameKr: '라네즈 립 슬리핑 마스크',
    category: 'k-beauty',
    subcategory: 'lipcare',
    price: 22.00,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 5234,
    badges: [],
    emoji: '💋',
    bgColor: '#fce4ec',
    description: 'Overnight lip treatment for soft, smooth lips. Berry flavor.',
    inStock: true
  },
  {
    id: 'kb-006',
    name: 'MISSHA BB Cream SPF42',
    nameKr: '미샤 BB크림 SPF42',
    category: 'k-beauty',
    subcategory: 'makeup',
    price: 12.99,
    originalPrice: 16.99,
    discount: 24,
    rating: 4.5,
    reviews: 2876,
    badges: ['sale'],
    emoji: '💄',
    bgColor: '#fce4ec',
    description: 'Perfect cover BB cream with sun protection. Natural finish.',
    inStock: true
  },

  // === K-POP ===
  {
    id: 'kp-001',
    name: 'BTS - [Proof] Anthology Album',
    nameKr: 'BTS 프루프 앤솔로지 앨범',
    category: 'k-pop',
    subcategory: 'albums',
    price: 42.99,
    originalPrice: null,
    discount: 0,
    rating: 4.9,
    reviews: 12543,
    badges: ['hot'],
    emoji: '💜',
    bgColor: '#ede7f6',
    description: 'Anthology album featuring the best of BTS. Includes photocards.',
    inStock: true
  },
  {
    id: 'kp-002',
    name: 'BLACKPINK Official Light Stick Ver.2',
    nameKr: '블랙핑크 공식 응원봉 Ver.2',
    category: 'k-pop',
    subcategory: 'lightstick',
    price: 54.99,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 4321,
    badges: [],
    emoji: '🩷',
    bgColor: '#fce4ec',
    description: 'Official BLACKPINK hammer-bong light stick with Bluetooth connectivity.',
    inStock: true
  },
  {
    id: 'kp-003',
    name: 'Stray Kids - ★★★★★ (5-STAR)',
    nameKr: '스트레이 키즈 5-STAR',
    category: 'k-pop',
    subcategory: 'albums',
    price: 24.99,
    originalPrice: 29.99,
    discount: 17,
    rating: 4.9,
    reviews: 7654,
    badges: ['sale'],
    emoji: '⭐',
    bgColor: '#fff3e0',
    description: '3rd Full Album with random photocard and poster.',
    inStock: true
  },
  {
    id: 'kp-004',
    name: 'NewJeans Photocard Binder Set',
    nameKr: '뉴진스 포토카드 바인더 세트',
    category: 'k-pop',
    subcategory: 'photocard',
    price: 18.99,
    originalPrice: null,
    discount: 0,
    rating: 4.7,
    reviews: 2134,
    badges: ['new'],
    emoji: '🐰',
    bgColor: '#e3f2fd',
    description: 'Cute binder with 50 sleeves for collecting your favorite photocards.',
    inStock: true
  },
  {
    id: 'kp-005',
    name: 'SEVENTEEN Official Carat Bong',
    nameKr: '세븐틴 공식 캐럿봉',
    category: 'k-pop',
    subcategory: 'lightstick',
    price: 49.99,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 3456,
    badges: [],
    emoji: '💎',
    bgColor: '#e8eaf6',
    description: 'Official SEVENTEEN diamond-shaped light stick Ver.3.',
    inStock: true
  },
  {
    id: 'kp-006',
    name: 'aespa - [Drama] 4th Mini Album',
    nameKr: '에스파 Drama 4th 미니앨범',
    category: 'k-pop',
    subcategory: 'albums',
    price: 19.99,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 5678,
    badges: ['new'],
    emoji: '🦋',
    bgColor: '#e8f5e9',
    description: 'Includes photobook, CD, photocard, and folded poster.',
    inStock: true
  },

  // === K-FASHION ===
  {
    id: 'kfa-001',
    name: 'Idol Airport Fashion Oversized Hoodie',
    nameKr: '아이돌 공항패션 오버사이즈 후디',
    category: 'k-fashion',
    subcategory: 'idol-style',
    price: 45.99,
    originalPrice: 59.99,
    discount: 23,
    rating: 4.6,
    reviews: 1234,
    badges: ['hot'],
    emoji: '🧥',
    bgColor: '#f3e5f5',
    description: 'Oversized hoodie inspired by idol airport fashion. Unisex design.',
    inStock: true
  },
  {
    id: 'kfa-002',
    name: 'Korean Streetwear Cargo Pants',
    nameKr: '한국 스트릿 카고 팬츠',
    category: 'k-fashion',
    subcategory: 'streetwear',
    price: 38.99,
    originalPrice: null,
    discount: 0,
    rating: 4.5,
    reviews: 876,
    badges: ['new'],
    emoji: '👖',
    bgColor: '#efebe9',
    description: 'Trendy wide-leg cargo pants popular in Hongdae street fashion.',
    inStock: true
  },
  {
    id: 'kfa-003',
    name: 'K-Pop Star Pearl Chain Necklace',
    nameKr: '케이팝 스타 진주 체인 목걸이',
    category: 'k-fashion',
    subcategory: 'jewelry',
    price: 15.99,
    originalPrice: null,
    discount: 0,
    rating: 4.7,
    reviews: 2345,
    badges: [],
    emoji: '📿',
    bgColor: '#fce4ec',
    description: 'Layered pearl chain necklace as seen on K-Pop idols.',
    inStock: true
  },
  {
    id: 'kfa-004',
    name: 'Stage Concept Cropped Leather Jacket',
    nameKr: '스테이지 컨셉 크롭 가죽 자켓',
    category: 'k-fashion',
    subcategory: 'idol-style',
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    rating: 4.8,
    reviews: 543,
    badges: ['sale'],
    emoji: '🧥',
    bgColor: '#263238',
    description: 'MV-inspired cropped leather jacket with silver hardware details.',
    inStock: true
  },
  {
    id: 'kfa-005',
    name: 'Korean Mini Crossbody Bag',
    nameKr: '한국 미니 크로스백',
    category: 'k-fashion',
    subcategory: 'bags',
    price: 29.99,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviews: 1567,
    badges: [],
    emoji: '👜',
    bgColor: '#efebe9',
    description: 'Compact crossbody bag popular with Korean fashion influencers.',
    inStock: true
  },
  {
    id: 'kfa-006',
    name: 'Idol-Style Silver Ring Set (5pcs)',
    nameKr: '아이돌 스타일 실버링 세트 5개',
    category: 'k-fashion',
    subcategory: 'accessories',
    price: 12.99,
    originalPrice: 18.99,
    discount: 32,
    rating: 4.4,
    reviews: 2100,
    badges: ['sale'],
    emoji: '💍',
    bgColor: '#eceff1',
    description: 'Stackable silver-tone ring set inspired by K-Pop idol accessories.',
    inStock: true
  }
];

const NEW_KPOP_ARRIVALS = [
  {
    id: 'nka-001',
    artist: 'ENHYPEN',
    title: 'ROMANCE : UNTOLD',
    type: 'Full Album',
    price: 26.99,
    emoji: '🦇',
    bgColor: '#1a1a2e',
    preorder: true
  },
  {
    id: 'nka-002',
    artist: 'IVE',
    title: "I'VE MINE",
    type: '1st EP',
    price: 22.99,
    emoji: '🦢',
    bgColor: '#2d1b69',
    preorder: false
  },
  {
    id: 'nka-003',
    artist: 'LE SSERAFIM',
    title: 'EASY',
    type: '3rd Mini Album',
    price: 21.99,
    emoji: '🔥',
    bgColor: '#c31432',
    preorder: true
  },
  {
    id: 'nka-004',
    artist: 'TXT',
    title: 'The Star Chapter: SANCTUARY',
    type: 'Full Album',
    price: 28.99,
    emoji: '⭐',
    bgColor: '#0f3460',
    preorder: true
  },
  {
    id: 'nka-005',
    artist: 'TWICE',
    title: 'STRATEGY',
    type: 'Special Album',
    price: 32.99,
    emoji: '🍭',
    bgColor: '#e84393',
    preorder: false
  }
];
